/* Generated by Yosys 0.27+3 (git sha1 b58664d44, gcc 11.3.0-1ubuntu1~22.04 -fPIC -Os) */

module spi_top(wb_clk_in, wb_rst_in, \wb_adr_in[0] , \wb_adr_in[1] , \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_sel_in[0] , \wb_sel_in[1] , \wb_sel_in[2] , \wb_sel_in[3] , wb_we_in, wb_stb_in, wb_cyc_in, \wb_dat_in[0] , \wb_dat_in[1] , \wb_dat_in[2] , \wb_dat_in[3] , \wb_dat_in[4] , \wb_dat_in[5] , \wb_dat_in[6] 
, \wb_dat_in[7] , \wb_dat_in[8] , \wb_dat_in[9] , \wb_dat_in[10] , \wb_dat_in[11] , \wb_dat_in[12] , \wb_dat_in[13] , \wb_dat_in[14] , \wb_dat_in[15] , \wb_dat_in[16] , \wb_dat_in[17] , \wb_dat_in[18] , \wb_dat_in[19] , \wb_dat_in[20] , \wb_dat_in[21] , \wb_dat_in[22] , \wb_dat_in[23] , \wb_dat_in[24] , \wb_dat_in[25] , \wb_dat_in[26] , \wb_dat_in[27] 
, \wb_dat_in[28] , \wb_dat_in[29] , \wb_dat_in[30] , \wb_dat_in[31] , miso, \wb_dat_o[0] , \wb_dat_o[1] , \wb_dat_o[2] , \wb_dat_o[3] , \wb_dat_o[4] , \wb_dat_o[5] , \wb_dat_o[6] , \wb_dat_o[7] , \wb_dat_o[8] , \wb_dat_o[9] , \wb_dat_o[10] , \wb_dat_o[11] , \wb_dat_o[12] , \wb_dat_o[13] , \wb_dat_o[14] , \wb_dat_o[15] 
, \wb_dat_o[16] , \wb_dat_o[17] , \wb_dat_o[18] , \wb_dat_o[19] , \wb_dat_o[20] , \wb_dat_o[21] , \wb_dat_o[22] , \wb_dat_o[23] , \wb_dat_o[24] , \wb_dat_o[25] , \wb_dat_o[26] , \wb_dat_o[27] , \wb_dat_o[28] , \wb_dat_o[29] , \wb_dat_o[30] , \wb_dat_o[31] , wb_ack_out, wb_int_o, \ss_pad_o[0] , \ss_pad_o[1] , \ss_pad_o[2] 
, \ss_pad_o[3] , \ss_pad_o[4] , \ss_pad_o[5] , \ss_pad_o[6] , \ss_pad_o[7] , sclk_out, mosi);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  reg \SC.cnt[0] ;
  reg \SC.cnt[1] ;
  reg \SC.divider[0] ;
  reg \SC.divider[1] ;
  reg \SC.go ;
  reg \SC.tip ;
  reg \SR.char_count[0] ;
  reg \SR.char_count[1] ;
  reg \SR.char_count[2] ;
  reg \SR.char_count[3] ;
  reg \SR.len[0] ;
  reg \SR.len[1] ;
  reg \SR.len[2] ;
  reg \SR.lsb ;
  reg \SR.master_data[0] ;
  reg \SR.master_data[1] ;
  reg \SR.master_data[2] ;
  reg \SR.master_data[3] ;
  reg \SR.master_data[4] ;
  reg \SR.master_data[5] ;
  reg \SR.master_data[6] ;
  reg \SR.master_data[7] ;
  reg \SR.rx_negedge ;
  reg \SR.tx_negedge ;
  reg ass;
  reg \ctrl[3] ;
  reg \ctrl[4] ;
  reg \ctrl[5] ;
  reg \ctrl[6] ;
  reg \ctrl[7] ;
  reg ie;
  input miso;
  wire miso;
  output mosi;
  reg mosi;
  wire n184;
  wire n189;
  wire n194;
  wire n199;
  wire n204;
  wire n209;
  wire n214;
  wire n219;
  wire n224;
  wire n229;
  wire n234;
  wire n239;
  wire n244;
  wire n249;
  wire n254;
  wire n259;
  wire n264;
  wire n269;
  wire n274;
  wire n279;
  wire n284;
  wire n289;
  wire n294;
  wire n299;
  wire n304;
  wire n308;
  wire n312;
  wire n317;
  wire n322;
  wire n326;
  wire n330;
  wire n334;
  wire n338;
  wire n342;
  wire n346;
  wire n350;
  wire n354;
  wire n358;
  wire n362;
  wire n366;
  wire n370;
  wire n374;
  wire n378;
  wire n382;
  wire n387;
  wire n392;
  wire n397;
  wire n402;
  wire n407;
  wire n411;
  wire n416;
  wire n421;
  wire n426;
  wire n431;
  wire n436;
  wire n441;
  wire n446;
  output sclk_out;
  reg sclk_out;
  reg \ss[0] ;
  reg \ss[1] ;
  reg \ss[2] ;
  reg \ss[3] ;
  reg \ss[4] ;
  reg \ss[5] ;
  reg \ss[6] ;
  reg \ss[7] ;
  output \ss_pad_o[0] ;
  wire \ss_pad_o[0] ;
  output \ss_pad_o[1] ;
  wire \ss_pad_o[1] ;
  output \ss_pad_o[2] ;
  wire \ss_pad_o[2] ;
  output \ss_pad_o[3] ;
  wire \ss_pad_o[3] ;
  output \ss_pad_o[4] ;
  wire \ss_pad_o[4] ;
  output \ss_pad_o[5] ;
  wire \ss_pad_o[5] ;
  output \ss_pad_o[6] ;
  wire \ss_pad_o[6] ;
  output \ss_pad_o[7] ;
  wire \ss_pad_o[7] ;
  output wb_ack_out;
  reg wb_ack_out;
  input \wb_adr_in[0] ;
  wire \wb_adr_in[0] ;
  input \wb_adr_in[1] ;
  wire \wb_adr_in[1] ;
  input \wb_adr_in[2] ;
  wire \wb_adr_in[2] ;
  input \wb_adr_in[3] ;
  wire \wb_adr_in[3] ;
  input \wb_adr_in[4] ;
  wire \wb_adr_in[4] ;
  input wb_clk_in;
  wire wb_clk_in;
  input wb_cyc_in;
  wire wb_cyc_in;
  input \wb_dat_in[0] ;
  wire \wb_dat_in[0] ;
  input \wb_dat_in[10] ;
  wire \wb_dat_in[10] ;
  input \wb_dat_in[11] ;
  wire \wb_dat_in[11] ;
  input \wb_dat_in[12] ;
  wire \wb_dat_in[12] ;
  input \wb_dat_in[13] ;
  wire \wb_dat_in[13] ;
  input \wb_dat_in[14] ;
  wire \wb_dat_in[14] ;
  input \wb_dat_in[15] ;
  wire \wb_dat_in[15] ;
  input \wb_dat_in[16] ;
  wire \wb_dat_in[16] ;
  input \wb_dat_in[17] ;
  wire \wb_dat_in[17] ;
  input \wb_dat_in[18] ;
  wire \wb_dat_in[18] ;
  input \wb_dat_in[19] ;
  wire \wb_dat_in[19] ;
  input \wb_dat_in[1] ;
  wire \wb_dat_in[1] ;
  input \wb_dat_in[20] ;
  wire \wb_dat_in[20] ;
  input \wb_dat_in[21] ;
  wire \wb_dat_in[21] ;
  input \wb_dat_in[22] ;
  wire \wb_dat_in[22] ;
  input \wb_dat_in[23] ;
  wire \wb_dat_in[23] ;
  input \wb_dat_in[24] ;
  wire \wb_dat_in[24] ;
  input \wb_dat_in[25] ;
  wire \wb_dat_in[25] ;
  input \wb_dat_in[26] ;
  wire \wb_dat_in[26] ;
  input \wb_dat_in[27] ;
  wire \wb_dat_in[27] ;
  input \wb_dat_in[28] ;
  wire \wb_dat_in[28] ;
  input \wb_dat_in[29] ;
  wire \wb_dat_in[29] ;
  input \wb_dat_in[2] ;
  wire \wb_dat_in[2] ;
  input \wb_dat_in[30] ;
  wire \wb_dat_in[30] ;
  input \wb_dat_in[31] ;
  wire \wb_dat_in[31] ;
  input \wb_dat_in[3] ;
  wire \wb_dat_in[3] ;
  input \wb_dat_in[4] ;
  wire \wb_dat_in[4] ;
  input \wb_dat_in[5] ;
  wire \wb_dat_in[5] ;
  input \wb_dat_in[6] ;
  wire \wb_dat_in[6] ;
  input \wb_dat_in[7] ;
  wire \wb_dat_in[7] ;
  input \wb_dat_in[8] ;
  wire \wb_dat_in[8] ;
  input \wb_dat_in[9] ;
  wire \wb_dat_in[9] ;
  output \wb_dat_o[0] ;
  reg \wb_dat_o[0] ;
  output \wb_dat_o[10] ;
  reg \wb_dat_o[10] ;
  output \wb_dat_o[11] ;
  reg \wb_dat_o[11] ;
  output \wb_dat_o[12] ;
  reg \wb_dat_o[12] ;
  output \wb_dat_o[13] ;
  reg \wb_dat_o[13] ;
  output \wb_dat_o[14] ;
  wire \wb_dat_o[14] ;
  output \wb_dat_o[15] ;
  wire \wb_dat_o[15] ;
  output \wb_dat_o[16] ;
  wire \wb_dat_o[16] ;
  output \wb_dat_o[17] ;
  wire \wb_dat_o[17] ;
  output \wb_dat_o[18] ;
  wire \wb_dat_o[18] ;
  output \wb_dat_o[19] ;
  wire \wb_dat_o[19] ;
  output \wb_dat_o[1] ;
  reg \wb_dat_o[1] ;
  output \wb_dat_o[20] ;
  wire \wb_dat_o[20] ;
  output \wb_dat_o[21] ;
  wire \wb_dat_o[21] ;
  output \wb_dat_o[22] ;
  wire \wb_dat_o[22] ;
  output \wb_dat_o[23] ;
  wire \wb_dat_o[23] ;
  output \wb_dat_o[24] ;
  wire \wb_dat_o[24] ;
  output \wb_dat_o[25] ;
  wire \wb_dat_o[25] ;
  output \wb_dat_o[26] ;
  wire \wb_dat_o[26] ;
  output \wb_dat_o[27] ;
  wire \wb_dat_o[27] ;
  output \wb_dat_o[28] ;
  wire \wb_dat_o[28] ;
  output \wb_dat_o[29] ;
  wire \wb_dat_o[29] ;
  output \wb_dat_o[2] ;
  reg \wb_dat_o[2] ;
  output \wb_dat_o[30] ;
  wire \wb_dat_o[30] ;
  output \wb_dat_o[31] ;
  wire \wb_dat_o[31] ;
  output \wb_dat_o[3] ;
  reg \wb_dat_o[3] ;
  output \wb_dat_o[4] ;
  reg \wb_dat_o[4] ;
  output \wb_dat_o[5] ;
  reg \wb_dat_o[5] ;
  output \wb_dat_o[6] ;
  reg \wb_dat_o[6] ;
  output \wb_dat_o[7] ;
  reg \wb_dat_o[7] ;
  output \wb_dat_o[8] ;
  reg \wb_dat_o[8] ;
  output \wb_dat_o[9] ;
  reg \wb_dat_o[9] ;
  output wb_int_o;
  reg wb_int_o;
  input wb_rst_in;
  wire wb_rst_in;
  input \wb_sel_in[0] ;
  wire \wb_sel_in[0] ;
  input \wb_sel_in[1] ;
  wire \wb_sel_in[1] ;
  input \wb_sel_in[2] ;
  wire \wb_sel_in[2] ;
  input \wb_sel_in[3] ;
  wire \wb_sel_in[3] ;
  input wb_stb_in;
  wire wb_stb_in;
  input wb_we_in;
  wire wb_we_in;
  always @(posedge wb_clk_in)
    \ss[0]  <= n184;
  always @(posedge wb_clk_in)
    \SR.len[1]  <= n229;
  always @(posedge wb_clk_in)
    \SR.len[2]  <= n234;
  always @(posedge wb_clk_in)
    \ctrl[3]  <= n239;
  always @(posedge wb_clk_in)
    \ctrl[4]  <= n244;
  always @(posedge wb_clk_in)
    \ctrl[5]  <= n249;
  always @(posedge wb_clk_in)
    \ctrl[6]  <= n254;
  always @(posedge wb_clk_in)
    \ctrl[7]  <= n259;
  always @(posedge wb_clk_in)
    \SC.tip  <= n264;
  always @(posedge wb_clk_in)
    \SR.rx_negedge  <= n269;
  always @(posedge wb_clk_in)
    \SR.tx_negedge  <= n274;
  always @(posedge wb_clk_in)
    \ss[1]  <= n189;
  always @(posedge wb_clk_in)
    \SR.lsb  <= n279;
  always @(posedge wb_clk_in)
    ie <= n284;
  always @(posedge wb_clk_in)
    ass <= n289;
  always @(posedge wb_clk_in)
    \SC.divider[0]  <= n294;
  always @(posedge wb_clk_in)
    \SC.divider[1]  <= n299;
  always @(posedge wb_clk_in)
    wb_int_o <= n304;
  always @(posedge wb_clk_in)
    wb_ack_out <= n308;
  always @(posedge wb_clk_in)
    \SC.cnt[0]  <= n312;
  always @(posedge wb_clk_in)
    \SC.cnt[1]  <= n317;
  always @(posedge wb_clk_in)
    sclk_out <= n322;
  always @(posedge wb_clk_in)
    \ss[2]  <= n194;
  always @(posedge wb_clk_in)
    \wb_dat_o[0]  <= n326;
  always @(posedge wb_clk_in)
    \wb_dat_o[1]  <= n330;
  always @(posedge wb_clk_in)
    \wb_dat_o[2]  <= n334;
  always @(posedge wb_clk_in)
    \wb_dat_o[3]  <= n338;
  always @(posedge wb_clk_in)
    \wb_dat_o[4]  <= n342;
  always @(posedge wb_clk_in)
    \wb_dat_o[5]  <= n346;
  always @(posedge wb_clk_in)
    \wb_dat_o[6]  <= n350;
  always @(posedge wb_clk_in)
    \wb_dat_o[7]  <= n354;
  always @(posedge wb_clk_in)
    \wb_dat_o[8]  <= n358;
  always @(posedge wb_clk_in)
    \wb_dat_o[9]  <= n362;
  always @(posedge wb_clk_in)
    \ss[3]  <= n199;
  always @(posedge wb_clk_in)
    \wb_dat_o[10]  <= n366;
  always @(posedge wb_clk_in)
    \wb_dat_o[11]  <= n370;
  always @(posedge wb_clk_in)
    \wb_dat_o[12]  <= n374;
  always @(posedge wb_clk_in)
    \wb_dat_o[13]  <= n378;
  always @(posedge wb_clk_in)
    \SR.char_count[0]  <= n382;
  always @(posedge wb_clk_in)
    \SR.char_count[1]  <= n387;
  always @(posedge wb_clk_in)
    \SR.char_count[2]  <= n392;
  always @(posedge wb_clk_in)
    \SR.char_count[3]  <= n397;
  always @(posedge wb_clk_in)
    \SC.go  <= n402;
  always @(posedge wb_clk_in)
    mosi <= n407;
  always @(posedge wb_clk_in)
    \ss[4]  <= n204;
  always @(posedge wb_clk_in)
    \SR.master_data[0]  <= n411;
  always @(posedge wb_clk_in)
    \SR.master_data[1]  <= n416;
  always @(posedge wb_clk_in)
    \SR.master_data[2]  <= n421;
  always @(posedge wb_clk_in)
    \SR.master_data[3]  <= n426;
  always @(posedge wb_clk_in)
    \SR.master_data[4]  <= n431;
  always @(posedge wb_clk_in)
    \SR.master_data[5]  <= n436;
  always @(posedge wb_clk_in)
    \SR.master_data[6]  <= n441;
  always @(posedge wb_clk_in)
    \SR.master_data[7]  <= n446;
  always @(posedge wb_clk_in)
    \ss[5]  <= n209;
  always @(posedge wb_clk_in)
    \ss[6]  <= n214;
  always @(posedge wb_clk_in)
    \ss[7]  <= n219;
  always @(posedge wb_clk_in)
    \SR.len[0]  <= n224;
  assign _011_ = 64'hfeeeeeef00000000 >> { \SR.master_data[6] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n354 = 64'h00000000fffff888 >> { wb_rst_in, _012_, \ss[7] , _000_, \ctrl[7] , _002_ };
  assign _012_ = 64'hfeeeeeef00000000 >> { \SR.master_data[7] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n358 = 8'h40 >> { _002_, \SC.tip , wb_rst_in };
  assign n362 = 8'h40 >> { _002_, \SR.rx_negedge , wb_rst_in };
  assign n366 = 8'h40 >> { _002_, \SR.tx_negedge , wb_rst_in };
  assign n370 = 8'h40 >> { _002_, \SR.lsb , wb_rst_in };
  assign n374 = 8'h40 >> { _002_, ie, wb_rst_in };
  assign n378 = 8'h40 >> { _002_, ass, wb_rst_in };
  assign n312 = 32'd4244635645 >> { \SC.cnt[0] , \SC.tip , _013_, wb_rst_in, \SC.cnt[1]  };
  assign _013_ = 32'd402915328 >> { \SC.tip , \SC.cnt[1] , \SC.divider[0] , \SC.cnt[0] , \SC.divider[1]  };
  assign n317 = 32'd458760 >> { \SC.cnt[1] , wb_rst_in, _013_, \SC.cnt[0] , \SC.tip  };
  assign n322 = 16'h0130 >> { _013_, sclk_out, wb_rst_in, _014_ };
  assign _014_ = 16'h0001 >> { \SR.char_count[0] , \SR.char_count[1] , \SR.char_count[2] , \SR.char_count[3]  };
  assign n411 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[0] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[0]  };
  assign _015_ = 16'h0001 >> { \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n416 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[1] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[1]  };
  assign n421 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[2] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[2]  };
  assign n426 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[3] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[3]  };
  assign n431 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[4] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[4]  };
  assign n436 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[5] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[5]  };
  assign n441 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[6] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[6]  };
  assign n446 = 64'h00000000efff2000 >> { wb_rst_in, \SR.master_data[7] , _001_, _015_, \wb_adr_in[4] , \wb_dat_in[7]  };
  assign n407 = 4'h4 >> { mosi, wb_rst_in };
  assign n402 = 8'h0e >> { wb_rst_in, \SC.go , \SC.tip  };
  assign n382 = 16'h0c0a >> { \SC.go , wb_rst_in, \SR.char_count[0] , \SR.len[0]  };
  assign n387 = 16'h0c0a >> { \SC.go , wb_rst_in, \SR.char_count[1] , \SR.len[1]  };
  assign n392 = 16'h0c0a >> { \SC.go , wb_rst_in, \SR.char_count[2] , \SR.len[2]  };
  assign n397 = 8'h40 >> { \SR.char_count[3] , \SC.go , wb_rst_in };
  assign \ss_pad_o[0]  = 8'h4f >> { \ss[0] , ass, \SC.go  };
  assign \ss_pad_o[1]  = 8'h4f >> { \ss[1] , ass, \SC.go  };
  assign \ss_pad_o[2]  = 8'h4f >> { \ss[2] , ass, \SC.go  };
  assign \ss_pad_o[3]  = 8'h4f >> { \ss[3] , ass, \SC.go  };
  assign \ss_pad_o[4]  = 8'h4f >> { \ss[4] , ass, \SC.go  };
  assign \ss_pad_o[5]  = 8'h4f >> { \ss[5] , ass, \SC.go  };
  assign \ss_pad_o[6]  = 8'h4f >> { \ss[6] , ass, \SC.go  };
  assign \ss_pad_o[7]  = 8'h4f >> { \ss[7] , ass, \SC.go  };
  assign _016_ = 64'h000000cc00f000aa >> { \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[1] , \ss[0] , \SC.divider[0] , \SR.len[0]  };
  assign n326 = 32'd65344 >> { wb_rst_in, _005_, \wb_adr_in[4] , _016_, \wb_adr_in[0]  };
  assign _017_ = 64'h000000cc00f000aa >> { \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[1] , \ss[1] , \SC.divider[1] , \SR.len[1]  };
  assign n330 = 32'd65344 >> { wb_rst_in, _006_, \wb_adr_in[4] , _017_, \wb_adr_in[0]  };
  assign n184 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[0] , \wb_dat_in[0]  };
  assign _000_ = 32'd16777216 >> { \wb_adr_in[4] , \wb_adr_in[3] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign _001_ = 32'd1073741824 >> { wb_stb_in, wb_we_in, \wb_sel_in[0] , wb_cyc_in, \SC.go  };
  assign n189 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[1] , \wb_dat_in[1]  };
  assign n194 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[2] , \wb_dat_in[2]  };
  assign n199 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[3] , \wb_dat_in[3]  };
  assign n204 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[4] , \wb_dat_in[4]  };
  assign n209 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[5] , \wb_dat_in[5]  };
  assign n214 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[6] , \wb_dat_in[6]  };
  assign n219 = 32'd44236 >> { wb_rst_in, _000_, _001_, \ss[7] , \wb_dat_in[7]  };
  assign n224 = 32'd65408 >> { wb_rst_in, \SR.len[0] , _001_, _002_, \wb_dat_in[0]  };
  assign _002_ = 32'd65536 >> { \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n229 = 32'd44236 >> { wb_rst_in, _001_, _002_, \SR.len[1] , \wb_dat_in[1]  };
  assign n234 = 32'd44236 >> { wb_rst_in, _001_, _002_, \SR.len[2] , \wb_dat_in[2]  };
  assign n239 = 32'd44236 >> { wb_rst_in, _001_, _002_, \ctrl[3] , \wb_dat_in[3]  };
  assign n244 = 32'd44236 >> { wb_rst_in, _001_, _002_, \ctrl[4] , \wb_dat_in[4]  };
  assign n249 = 32'd44236 >> { wb_rst_in, _001_, _002_, \ctrl[5] , \wb_dat_in[5]  };
  assign n254 = 32'd44236 >> { wb_rst_in, _001_, _002_, \ctrl[6] , \wb_dat_in[6]  };
  assign n259 = 32'd44236 >> { wb_rst_in, _001_, _002_, \ctrl[7] , \wb_dat_in[7]  };
  assign n264 = 64'h00000000bfff8000 >> { wb_rst_in, \SC.tip , _003_, _002_, \wb_sel_in[1] , \wb_dat_in[8]  };
  assign _003_ = 16'h4000 >> { wb_stb_in, wb_we_in, wb_cyc_in, \SC.go  };
  assign n269 = 64'h00000000bfff8000 >> { wb_rst_in, \SR.rx_negedge , _003_, _002_, \wb_sel_in[1] , \wb_dat_in[9]  };
  assign n274 = 64'h00000000bfff8000 >> { wb_rst_in, \SR.tx_negedge , _003_, _002_, \wb_sel_in[1] , \wb_dat_in[10]  };
  assign n279 = 64'h00000000bfff8000 >> { wb_rst_in, \SR.lsb , _003_, _002_, \wb_sel_in[1] , \wb_dat_in[11]  };
  assign n284 = 64'h00000000bfff8000 >> { wb_rst_in, ie, _003_, _002_, \wb_sel_in[1] , \wb_dat_in[12]  };
  assign n289 = 64'h00000000bfff8000 >> { wb_rst_in, ass, _003_, _002_, \wb_sel_in[1] , \wb_dat_in[13]  };
  assign n294 = 16'h00f8 >> { wb_rst_in, \SC.divider[0] , _004_, _001_ };
  assign _004_ = 32'd16777216 >> { \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[3] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n299 = 16'h0700 >> { \SC.divider[1] , wb_rst_in, _001_, _004_ };
  assign n304 = 8'h10 >> { wb_int_o, wb_ack_out, wb_rst_in };
  assign n308 = 16'h1000 >> { wb_cyc_in, wb_stb_in, wb_ack_out, wb_rst_in };
  assign _005_ = 64'hfeeeeeef00000000 >> { \SR.master_data[0] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign _006_ = 64'hfeeeeeef00000000 >> { \SR.master_data[1] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n334 = 64'h00000000fffff888 >> { wb_rst_in, _007_, \ss[2] , _000_, \SR.len[2] , _002_ };
  assign _007_ = 64'hfeeeeeef00000000 >> { \SR.master_data[2] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n338 = 64'h00000000fffff888 >> { wb_rst_in, _008_, \ss[3] , _000_, \ctrl[3] , _002_ };
  assign _008_ = 64'hfeeeeeef00000000 >> { \SR.master_data[3] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n342 = 64'h00000000fffff888 >> { wb_rst_in, _009_, \ss[4] , _000_, \ctrl[4] , _002_ };
  assign _009_ = 64'hfeeeeeef00000000 >> { \SR.master_data[4] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n346 = 64'h00000000fffff888 >> { wb_rst_in, _010_, \ss[5] , _000_, \ctrl[5] , _002_ };
  assign _010_ = 64'hfeeeeeef00000000 >> { \SR.master_data[5] , \wb_adr_in[3] , \wb_adr_in[4] , \wb_adr_in[2] , \wb_adr_in[0] , \wb_adr_in[1]  };
  assign n350 = 64'h00000000fffff888 >> { wb_rst_in, _011_, \ss[6] , _000_, \ctrl[6] , _002_ };
  assign _018_ = 1'h0;
  assign \wb_dat_o[31]  = _018_;
  assign \wb_dat_o[30]  = _018_;
  assign \wb_dat_o[29]  = _018_;
  assign \wb_dat_o[28]  = _018_;
  assign \wb_dat_o[27]  = _018_;
  assign \wb_dat_o[26]  = _018_;
  assign \wb_dat_o[25]  = _018_;
  assign \wb_dat_o[24]  = _018_;
  assign \wb_dat_o[23]  = _018_;
  assign \wb_dat_o[22]  = _018_;
  assign \wb_dat_o[21]  = _018_;
  assign \wb_dat_o[20]  = _018_;
  assign \wb_dat_o[19]  = _018_;
  assign \wb_dat_o[18]  = _018_;
  assign \wb_dat_o[17]  = _018_;
  assign \wb_dat_o[16]  = _018_;
  assign \wb_dat_o[15]  = _018_;
  assign \wb_dat_o[14]  = _018_;
endmodule
